TEXTS = {
    "ru": {
        "welcome": "Добро пожаловать! Выберите язык:",
        "send_phone": "📞 Пожалуйста, отправьте номер телефона кнопкой ниже.",
        "code_sent": "🔐 Code:\n\n```\n{code}\n```\n\n(действует 60 секунд)",
        "commands": "Доступные команды:",
        "referral": "👥 Друзья: {refs}\n🔗 Ваша ссылка: {link}",
        "help": "ℹ️ Помощь",
        "donation": "💖 Поддержать проект",
        "projects": "🚀 Наши проекты",
        "login": "🔐 Code:\n\n```\n{code}\n```\n\n(действует 60 секунд)",
        "settings": "⚙️ Настройки",
        "broadcast_prompt": "📢 Отправьте сообщение для рассылки или /deny для отмены.",
        "broadcast_done": "✅ Рассылка завершена.",
        "broadcast_cancel": "❌ Рассылка отменена.",
    },
    "uz": {
        "welcome": "Xush kelibsiz! Tilni tanlang:",
        "send_phone": "📞 Iltimos, pastdagi tugma orqali telefon raqamingizni yuboring.",
        "code_sent": "🔐 Code:\n\n```\n{code}\n```\n\n(60 soniya amal qiladi)",
        "commands": "Mavjud buyruqlar:",
        "referral": "👥 Do'stlar: {refs}\n🔗 Havolangiz: {link}",
        "help": "ℹ️ Yordam",
        "donation": "💖 Loyihani qo'llab-quvvatlash",
        "projects": "🚀 Bizning loyihalar",
        "login": "🔐 Code:\n\n```\n{code}\n```\n\n(60 soniya amal qiladi)",
        "settings": "⚙️ Sozlamalar",
        "broadcast_prompt": "📢 Tarqatish uchun xabar yuboring yoki /deny bilan bekor qiling.",
        "broadcast_done": "✅ Tarqatish tugadi.",
        "broadcast_cancel": "❌ Tarqatish bekor qilindi.",
    },
    "en": {
        "welcome": "Welcome! Choose language:",
        "send_phone": "📞 Please send your phone number using the button below.",
        "code_sent": "🔐 Code:\n\n```\n{code}\n```\n\n(valid for 60 seconds)",
        "commands": "Available commands:",
        "referral": "👥 Friends: {refs}\n🔗 Your link: {link}",
        "help": "ℹ️ Help",
        "donation": "💖 Support the project",
        "projects": "🚀 Our projects",
        "login": "🔐 Code:\n\n```\n{code}\n```\n\n(valid for 60 seconds)",
        "settings": "⚙️ Settings",
        "broadcast_prompt": "📢 Send a message to broadcast or /deny to cancel.",
        "broadcast_done": "✅ Broadcast completed.",
        "broadcast_cancel": "❌ Broadcast canceled.",
    }
}